services:
  dev:
    image: mcr.microsoft.com/devcontainers/rust:1-bookworm 
    volumes:
      # Mount the root folder that contains .git
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - repos:/etc/komodo/repos
      - stacks:/etc/komodo/stacks
    command: sleep infinity
    ports:
      - "9120:9120"
    environment:
      KOMODO_HOST: http://localhost:9120
      KOMODO_FIRST_SERVER: http://localhost:8120
      KOMODO_DATABASE_ADDRESS: db
      KOMODO_ENABLE_NEW_USERS: true
      KOMODO_LOCAL_AUTH: true
      KOMODO_JWT_SECRET: a_random_secret
      VITE_KOMODO_HOST: http://localhost:9120
      KOMODO_CORS_ALLOWED_ORIGINS: http://localhost:5173
      KOMODO_CORS_ALLOW_CREDENTIALS: true
      PERIPHERY_SSL_ENABLED: false
      KOMODO_SESSION_ALLOW_CROSS_SITE: true
    links:
      - db
    # ...

  db:
    extends:
      file: ../dev.compose.yaml
      service: ferretdb

volumes:
  data:
  repo-cache:
  repos:
  stacks:
